repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910  # Use the desired version of Mypy
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]
