repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        args: [src]
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        args: [tests]
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
