name: 'Python project deploy'

on:
  push:
    branches:
      - main
      - 'ha*'
  pull_request:
    branches:
      - main
      - 'ha*'

jobs:
  deploy:
    name: Lint-Format-Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install -E dev

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files

      - name: Run pylint
        run: poetry run pylint src

      - name: Run mypy
        run: poetry run mypy src

      - name: Run isort
        run: poetry run isort src tests

      - name: Run black
        run: poetry run black src tests

      - name: Run pytest
        run: poetry run pytest tests
